[package]
name = "qre-gui"
version = "2.2.2"
description = "QRE Locker"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
# Tauri
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# Crypto
aes-gcm = "0.10"
argon2 = { version = "0.5", features = ["std"] }
pqcrypto-kyber = "0.8"
pqcrypto-traits = "0.3.5"
rand = "0.8"
rand_chacha = "0.3"
sha2 = "0.10"
zeroize = { version = "1", features = ["derive"] }
bincode = "1.3"
zstd = "0.13"

# Utils
anyhow = "1.0"
thiserror = "1.0"
chrono = "0.4"
directories = "5.0" #
uuid = { version = "1.0", features = ["v4", "fast-rng"] }
tauri-plugin-fs = "2.4.4"
sysinfo = "0.30"
zip = "0.6"
walkdir = "2" 
tauri-plugin-clipboard-manager = "2"
